baseURL ="https://hugo-paper.vercel.app/"
# title = "Hugo Themes"
author = "Alejandra Citlalli"
copyright = "© 2024, Ale"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "paper"
title = "My Personal Blog"

[params]
  color = 'light'

 # twitter = '' #Intento de quitarlo
  github = 'citla-aly' #github.com/citla-aly
  linkedin = 'alejandra-citlalli-pacheco-tovar' #https://www.linkedin.com/in/alejandra-citlalli-pacheco-tovar/

avatar = 'alejandra.ptovar@gmail.com'
  name = 'Alejandra Citlalli Pacheco Tovar'
  bio = 'I am passionate about science, art, food, sports, and traveling.'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
